version: '1.0'

networks:
  compose-network:
    driver: bridge

services:  
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root 
    
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root 
      - ME_CONFIG_MONGODB_SERVER=mongo-db 
    depends_on:
      - mongo-db